### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by Shkitzberg** [SolRacht/writing.com-archival#9]
When I try to get an interactive, this happens.

`C:\Users\(me)\writing>python ./run.py get (story id)`
`Logging in...`
`Traceback (most recent call last):`
 ` File "./run.py", line 2, in <module>`
`    from archiver import archive, archive_search, update_archive, is_item_id`
`  File "C:\Users\(me)\writing\archiver.py", line 1, in <module>`
`    from scraper import get_chapter_list, get_search_ids`
`  File "C:\Users\(me)\writing\scraper.py", line 8, in <module>`
`    from session import get_page`
`  File "C:\Users\(me)\writing\session.py", line 81, in <module>`
`    __reload_session()`
`  File "C:\Users\(me)\writing\session.py", line 31, in __reload_session`
`    __log_in()`
`  File "C:\Users\(me)\writing\session.py", line 61, in __log_in`
`    username_form = login_form.find("input",type="text")`
`AttributeError: 'NoneType' object has no attribute 'find'`

Trying 'chmod' gives me this:

`C:\Users\(me)\writing>chmod +x run.py`
`chmod is not recognized as an internal or external command,`
`operable program or batch file.`

`C:\Users\(me)\writing>python chmod +x run.py`
`python: can't open file 'chmod': [Errno 2] No such file or directory`

**Comment by reederda** [comment]
I am having the same issue (minus the chmod problem). Running some Google searches seems to indicate there's a missing function call of some sort, somewhere in the code.

**Comment by SolRacht** [comment]
Hey there,

`chmod` is a Linux utility. You appear to be using Windows. You may be able to just run `python run.py` without needing the `chmod` command. You should know that I've never run the program on Windows.

That said, I am no longer actively maintaining this repository, and I strongly doubt it will work if it is run.

**Comment by SolRacht** [comment]
My apologies!

**Comment by leeolder** [comment]
I have created a pull request that should sort this issue. I have only tested this on Linux but i was getting the same error, and is now working perfectly.
It seemed to be an error with writing.com now using ssl, so i replaced http with https in /session.py

**Comment by Shkitzberg** [comment]
Thank you for addressing this issue.

I can now type in my username, but now it will not confirm after pressing 'y'. Tried every single key besides 'y' and 'n' and this same prompt still comes up every time. Tried setting the keyboard to English and on a drive besides C, still nothing.

`C:\Users\(me)\writing>python ./run.py get (story id)`
`Logging in...`
`Enter your username and password for writing.com.`
`Enter your username: (user)`
`you typed (user). is this correct?`
`[y/n]:`
`You must type either y or n.`
`[y/n]:`
`You must type either y or n.`
`[y/n]:`

**Comment by leeolder** [comment]
@Shkitzberg hmm, strange one. Unfortunately i can't reproduce this. I would doubt which drive its on would matter, and just for reference i'm using the English (UK) keyboard, but again i doubt this would make a difference.

However i did find an alternative to pressing the 'y' button. Instead of pressing 'y', copy the character to your clipboard, and paste it into your terminal. The part where you enter your username should automatically progress when a character is detected, and when you enter a password you will need to paste it in then press return to progress.

If you have a file named 'session' try deleting that and trying again. Don't remove the file called 'session.py'.

If that doesn't work can you supply what OS your using, i'm running it on Ubuntu 16.04, ~~but also have a windows 10 i can try on if needed.~~

* Edit - my Windows 10 machine died...
